"""
MetaLearnX — LLM Agent Provider
Uses LiteLLM to synthesize zero-shot hyperparameter search space bounds from dataset properties.
Provides graceful fallbacks if API limits or errors occur.
"""

from __future__ import annotations

import json
from typing import Any, Dict, Optional

from loguru import logger
from pydantic import BaseModel, Field

try:
    import litellm
    LITELLM_AVAILABLE = True
except ImportError:
    LITELLM_AVAILABLE = False


class RandomForestBounds(BaseModel):
    n_estimators: list[int] = Field(..., min_length=2, max_length=2, description="[min, max] trees")
    max_depth: list[int] = Field(..., min_length=2, max_length=2, description="[min, max] depth")

class XGBoostBounds(BaseModel):
    n_estimators: list[int] = Field(..., min_length=2, max_length=2, description="[min, max] trees")
    max_depth: list[int] = Field(..., min_length=2, max_length=2, description="[min, max] depth")
    learning_rate: list[float] = Field(..., min_length=2, max_length=2, description="[min, max] learning rate")

class OptunaSearchSpaceSchema(BaseModel):
    """Rigorous schema outlining bounded variables for models based on dataset properties."""
    random_forest: RandomForestBounds
    xgboost: XGBoostBounds
    reasoning: str = Field(..., description="Brief methodological justification for these bounds based on the dataset properties")


class LLMAgentProvider:
    """
    Interfaces with Large Language Models (LLMs) to synthesize data-driven optimization boundaries.
    Defaults to using Groq (llama3-70b-8192) via LiteLLM for high-speed, cost-effective inference.
    """

    def __init__(self, model_name: str = "groq/llama3-70b-8192"):
        self.model_name = model_name

    def synthesize_search_space(
        self,
        dataset_profile: dict,
        description: Optional[str] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Uses an LLM to recommend min/max bounds for hyperparameter search spaces.
        Requires dataset physical properties (rows, columns, class imbalance).
        """
        if not LITELLM_AVAILABLE:
            logger.warning("LiteLLM not available. Skipping LLM search space synthesis.")
            return None

        # Build prompt payload
        system_prompt = (
            "You are an Elite Principal Machine Learning Engineer. "
            "Given a dataset profile and description, your task is to recommend Optuna hyperparameter "
            "search space boundaries for Random Forest and XGBoost.\n\n"
            "Rules:\n"
            "1. Prevent overfitting: smaller depth for low-sample datasets.\n"
            "2. Ensure speed: smaller n_estimators for giant datasets.\n"
            "3. Output MUST perfectly match the JSON schema constraints.\n"
        )

        user_content = f"Dataset Profile Summary:\n{json.dumps(dataset_profile, indent=2)}\n"
        if description:
            user_content += f"\nDataset Description / Context:\n{description}\n"

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content}
        ]

        try:
            # Make the LiteLLM call using structured JSON format parsing
            logger.info(f"Synthesizing search space bounds via LLM ({self.model_name})...")
            response = litellm.completion(
                model=self.model_name,
                messages=messages,
                response_format=OptunaSearchSpaceSchema,
                temperature=0.1,  # Keep low for consistency
                max_tokens=600
            )

            # Extract json string generated by the LLM
            content = response.choices[0].message.content
            
            # The schema dictates output, parse it
            parsed_bounds = OptunaSearchSpaceSchema.model_validate_json(content)
            
            # Convert models to dictionaries suitable for optimizer.py injection
            result = {
                "random_forest": {
                    "n_estimators": tuple(parsed_bounds.random_forest.n_estimators),
                    "max_depth": tuple(parsed_bounds.random_forest.max_depth),
                },
                "xgboost": {
                    "n_estimators": tuple(parsed_bounds.xgboost.n_estimators),
                    "max_depth": tuple(parsed_bounds.xgboost.max_depth),
                },
                "llm_reasoning": parsed_bounds.reasoning
            }
            logger.info("Successfully received LLM-synthesized search bounds.")
            return result

        except Exception as e:
            logger.warning(f"LLM Search Space Synthesis failed. Proceeding with fallbacks. Error: {e}")
            return None

# Singleton
_llm_provider_instance: Optional[LLMAgentProvider] = None

def get_llm_provider() -> LLMAgentProvider:
    global _llm_provider_instance
    if _llm_provider_instance is None:
        _llm_provider_instance = LLMAgentProvider()
    return _llm_provider_instance
